import React from 'react';
import { 
  Monitor, 
  Settings, 
  Folder, 
  Globe, 
  Calculator, 
  FileText, 
  Mail, 
  Music, 
  Video, 
  Camera,
  MessageSquare,
  LayoutGrid,
  Ghost,
  Chrome,
  Mail as Gmail,
  Map as GoogleMaps,
  Cloud as GoogleDrive,
  FileText as GoogleDocs,
  Table as GoogleSheets,
  Presentation as GoogleSlides,
  Youtube,
  Calendar as GoogleCalendar,
  Image as GooglePhotos,
  Activity,
  Terminal as TerminalIcon,
  Clock as ClockIcon,
  Palette as PaintIcon,
  Scissors as SnippingIcon,
  StickyNote,
  Store,
  Users as TeamsIcon,
  Cloud as OneDriveIcon,
  Gamepad as XboxIcon,
  Cpu,
  List,
  Database as RegistryIcon,
  ShieldCheck as SecurityIcon,
  Search,
  Shield,
  ShieldCheck,
} from 'lucide-react';

export const APPS = [
  { id: 'explorer', name: 'File Explorer', icon: Folder, color: 'text-yellow-500' },
  { id: 'taskmgr', name: 'Task Manager', icon: Activity, color: 'text-blue-500' },
  { id: 'terminal', name: 'Terminal', icon: TerminalIcon, color: 'text-slate-700' },
  { id: 'edge', name: 'Microsoft Edge', icon: Globe, color: 'text-blue-500' },
  { id: 'chrome', name: 'Google Chrome', icon: Chrome, color: 'text-red-500' },
  { id: 'google', name: 'Google', icon: Search, color: 'text-blue-500' },
  { id: 'gmail', name: 'Gmail', icon: Gmail, color: 'text-red-600' },
  { id: 'youtube', name: 'YouTube', icon: Youtube, color: 'text-red-700' },
  { id: 'photos', name: 'Photos', icon: GooglePhotos, color: 'text-blue-400' },
  { id: 'googleone', name: 'Google One', icon: ShieldCheck, color: 'text-blue-600' },
  { id: 'playstore', name: 'Play Store', icon: Store, color: 'text-green-600' },
  { id: 'maps', name: 'Google Maps', icon: GoogleMaps, color: 'text-green-600' },
  { id: 'drive', name: 'Google Drive', icon: GoogleDrive, color: 'text-blue-500' },
  { id: 'docs', name: 'Google Docs', icon: GoogleDocs, color: 'text-blue-600' },
  { id: 'sheets', name: 'Google Sheets', icon: GoogleSheets, color: 'text-green-700' },
  { id: 'slides', name: 'Google Slides', icon: GoogleSlides, color: 'text-yellow-600' },
  { id: 'calendar', name: 'Calendar', icon: GoogleCalendar, color: 'text-blue-400' },
  { id: 'settings', name: 'Settings', icon: Settings, color: 'text-gray-500' },
  { id: 'calculator', name: 'Calculator', icon: Calculator, color: 'text-blue-600' },
  { id: 'notepad', name: 'Notepad', icon: FileText, color: 'text-blue-400' },
  { id: 'paint', name: 'Paint', icon: PaintIcon, color: 'text-orange-500' },
  { id: 'clock', name: 'Clock', icon: ClockIcon, color: 'text-blue-400' },
  { id: 'snipping', name: 'Snipping Tool', icon: SnippingIcon, color: 'text-slate-400' },
  { id: 'stickynotes', name: 'Sticky Notes', icon: StickyNote, color: 'text-yellow-400' },
  { id: 'teams', name: 'Microsoft Teams', icon: TeamsIcon, color: 'text-blue-600' },
  { id: 'onedrive', name: 'OneDrive', icon: OneDriveIcon, color: 'text-blue-400' },
  { id: 'xbox', name: 'Xbox', icon: XboxIcon, color: 'text-green-600' },
  { id: 'store', name: 'Microsoft Store', icon: Store, color: 'text-blue-600' },
  { id: 'ghost', name: 'Ghost Chat', icon: Ghost, color: 'text-green-500' },
  { id: 'vault', name: 'Ghost Vault', icon: Shield, color: 'text-emerald-500' },
  { id: 'recorder', name: 'Screen Recorder', icon: Video, color: 'text-red-500' },
  { id: 'security', name: 'Windows Security', icon: SecurityIcon, color: 'text-blue-500' },
  { id: 'devicemgr', name: 'Device Manager', icon: Cpu, color: 'text-slate-500' },
  { id: 'services', name: 'Services', icon: List, color: 'text-slate-500' },
  { id: 'regedit', name: 'Registry Editor', icon: RegistryIcon, color: 'text-blue-500' },
];
